import React from 'react';

import humanReadableHyperlinks from 'src/components/assets/img/human_readable_hyperlinks.png';
import {ImageBox} from 'src/components/commons/image';

const Mechanism = () => {
    return (
        <>
            <p>
                {'In general, hyperlinking is the process of creating a link between one web page or document and another by embedding a clickable link in them.'}
            </p>
            <p>
                {'The hyperlinking mechanism in CS-CONNECT allows users to easily find and share objects, or their properties, with just a few clicks using '}<b>{'hyperlinks auto-generated by the platform.'}</b>
                <br/>
                {'A hyperlink is a way to refer to an object and its properties compactly. It allows to quickly navigate between the object\'s details and the discussion about it, and reference the object in other discussions.'}
                <br/>
                {'Objects and their properties are required to have a unique ID to ensure that they can be referenced unambiguously through the hyperlinking mechanism.'}
            </p>
            <p>{'Hyperlinks are '}<b>{'human-readable'}</b>{'.'}</p>
            <ImageBox
                src={humanReadableHyperlinks}
                alt='Human-readable Hyperlinks'
            />
        </>
    );
};

export default Mechanism;
