---
environmentConfig:
  showOptionsConfig:
    showAddChannelButton: true
    showDefaultChannels: true
organizations:
  - name: Ecosystem
    id: "0"
    description: This organization is for the whole ecosystem
    isEcosystem: true
    sections:
      - name: Ecosystem Issues
        id: "0"
        isIssues: true
        url: http://localhost:3000/all-data-provider/issues
        widgets:
          - type: channel
  - name: Spazio 1
    id: "9"
    description: Il primo spazio di lavoro
    sections:
      - name: Alleanze stipulate per Paese
        id: "104"
        url: http://localhost:3000/all-data-provider/organizations/9/chartsCountryCounts
        widgets:
          - name: Alleanze stipulate per Paese
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/9/chartsCountryCounts/:id/data
          - type: channels
      - name: Alleanze stipulate per Generazione
        id: "105"
        url: http://localhost:3000/all-data-provider/organizations/9/chartsAlliancesPerGeneration
        widgets:
          - name: Paesi con numero di Alleanze stipulate per ogni Generazione
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/9/chartsAlliancesPerGeneration/:id/data
          - type: channels
      - name: Numero di Università per numero di Alleanze
        id: "106"
        url: http://localhost:3000/all-data-provider/organizations/9/chartsUniversitiesInvolved
        widgets:
          - name: Numero di Università coinvolte per numero di Alleanze
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/9/chartsUniversitiesInvolved/:id/data
          - type: channels
      - name: Alleanze Europee
        id: "107"
        url: http://localhost:3000/all-data-provider/organizations/9/chartsEuropeanAlliances
        widgets:
          - name: Numero di Alleanze Europee
            type: chart
            chartType: simple-line
            url: http://localhost:3000/all-data-provider/organizations/9/chartsEuropeanAlliances/:id/data
          - type: channels
  - name: Spazio 2
    id: "10"
    description: Il secondo spazio di lavoro
    sections:
      - name: Alleanze stipulate per Paese
        id: "108"
        url: http://localhost:3000/all-data-provider/organizations/10/chartsCountryCounts
        widgets:
          - name: Alleanze stipulate per Paese
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/10/chartsCountryCounts/:id/data
          - type: channels
      - name: Alleanze stipulate per Generazione
        id: "109"
        url: http://localhost:3000/all-data-provider/organizations/10/chartsAlliancesPerGeneration
        widgets:
          - name: Paesi con numero di Alleanze stipulate per ogni Generazione
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/10/chartsAlliancesPerGeneration/:id/data
          - type: channels
      - name: Numero di Università per numero di Alleanze
        id: "110"
        url: http://localhost:3000/all-data-provider/organizations/10/chartsUniversitiesInvolved
        widgets:
          - name: Numero di Università coinvolte per numero di Alleanze
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/10/chartsUniversitiesInvolved/:id/data
          - type: channels
      - name: Alleanze Europee
        id: "111"
        url: http://localhost:3000/all-data-provider/organizations/10/chartsEuropeanAlliances
        widgets:
          - name: Numero di Alleanze Europee
            type: chart
            chartType: simple-line
            url: http://localhost:3000/all-data-provider/organizations/10/chartsEuropeanAlliances/:id/data
          - type: channels
  - name: Spazio 3
    id: "11"
    description: Il terzo spazio di lavoro
    sections:
      - name: Alleanze stipulate per Paese
        id: "112"
        url: http://localhost:3000/all-data-provider/organizations/11/chartsCountryCounts
        widgets:
          - name: Alleanze stipulate per Paese
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/11/chartsCountryCounts/:id/data
          - type: channels
      - name: Alleanze stipulate per Generazione
        id: "113"
        url: http://localhost:3000/all-data-provider/organizations/11/chartsAlliancesPerGeneration
        widgets:
          - name: Paesi con numero di Alleanze stipulate per ogni Generazione
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/11/chartsAlliancesPerGeneration/:id/data
          - type: channels
      - name: Numero di Università per numero di Alleanze
        id: "114"
        url: http://localhost:3000/all-data-provider/organizations/11/chartsUniversitiesInvolved
        widgets:
          - name: Numero di Università coinvolte per numero di Alleanze
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/11/chartsUniversitiesInvolved/:id/data
          - type: channels
      - name: Alleanze Europee
        id: "115"
        url: http://localhost:3000/all-data-provider/organizations/11/chartsEuropeanAlliances
        widgets:
          - name: Numero di Alleanze Europee
            type: chart
            chartType: simple-line
            url: http://localhost:3000/all-data-provider/organizations/11/chartsEuropeanAlliances/:id/data
          - type: channels
  - name: Spazio 4
    id: "12"
    description: Il quarto spazio di lavoro
    sections:
      - name: Alleanze stipulate per Paese
        id: "116"
        url: http://localhost:3000/all-data-provider/organizations/12/chartsCountryCounts
        widgets:
          - name: Alleanze stipulate per Paese
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/12/chartsCountryCounts/:id/data
          - type: channels
      - name: Alleanze stipulate per Generazione
        id: "117"
        url: http://localhost:3000/all-data-provider/organizations/12/chartsAlliancesPerGeneration
        widgets:
          - name: Paesi con numero di Alleanze stipulate per ogni Generazione
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/12/chartsAlliancesPerGeneration/:id/data
          - type: channels
      - name: Numero di Università per numero di Alleanze
        id: "118"
        url: http://localhost:3000/all-data-provider/organizations/12/chartsUniversitiesInvolved
        widgets:
          - name: Numero di Università coinvolte per numero di Alleanze
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/12/chartsUniversitiesInvolved/:id/data
          - type: channels
      - name: Alleanze Europee
        id: "119"
        url: http://localhost:3000/all-data-provider/organizations/12/chartsEuropeanAlliances
        widgets:
          - name: Numero di Alleanze Europee
            type: chart
            chartType: simple-line
            url: http://localhost:3000/all-data-provider/organizations/12/chartsEuropeanAlliances/:id/data
          - type: channels
  - name: Spazio 5
    id: "13"
    description: Il quarto spazio di lavoro
    sections:
      - name: Alleanze stipulate per Paese
        id: "120"
        url: http://localhost:3000/all-data-provider/organizations/13/chartsCountryCounts
        widgets:
          - name: Alleanze stipulate per Paese
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/13/chartsCountryCounts/:id/data
          - type: channels
      - name: Alleanze stipulate per Generazione
        id: "121"
        url: http://localhost:3000/all-data-provider/organizations/13/chartsAlliancesPerGeneration
        widgets:
          - name: Paesi con numero di Alleanze stipulate per ogni Generazione
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/13/chartsAlliancesPerGeneration/:id/data
          - type: channels
      - name: Numero di Università per numero di Alleanze
        id: "122"
        url: http://localhost:3000/all-data-provider/organizations/13/chartsUniversitiesInvolved
        widgets:
          - name: Numero di Università coinvolte per numero di Alleanze
            type: chart
            chartType: simple-bar
            url: http://localhost:3000/all-data-provider/organizations/13/chartsUniversitiesInvolved/:id/data
          - type: channels
      - name: Alleanze Europee
        id: "123"
        url: http://localhost:3000/all-data-provider/organizations/13/chartsEuropeanAlliances
        widgets:
          - name: Numero di Alleanze Europee
            type: chart
            chartType: simple-line
            url: http://localhost:3000/all-data-provider/organizations/13/chartsEuropeanAlliances/:id/data
          - type: channels
    widgets: []
